version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: authgetway-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: authgetway
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: authgetway-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authgetway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  mysql_data:
