server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/authgetway}
    username: ${SPRING_DATASOURCE_USERNAME:auth}
    password: ${SPRING_DATASOURCE_PASSWORD:auth}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    gateway:
      routes:
        - id: jobfinder
          uri: http://jobfinder-service:8081
          predicates:
            - Path=/jobs/**
          filters:
            - StripPrefix=1
        - id: eventhandler
          uri: http://eventhandler-service:8082
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=1